import Config

# Configure your database
config :slack_rewriter, SlackRewriter.Repo,
  username: "postgres",
  password: System.get_env("postgres_pwd"),
  hostname: "postgres",
  database: "slack_rewriter_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :slack_rewriter, :slack,
  slack_oauth_redirect:
    System.get_env("slack_app_oauth_redirect")

config :slack_rewriter, :app,
  app_secret: System.get_env("slack_app_secret"),
  app_id: System.get_env("slack_app_id"),
  app_bot_token: System.get_env("slack_app_bot_token"),
  app_signing_secret: System.get_env("slack_app_signing_secret")

# config the cloak.ecto vault
config :slack_rewriter, SlackRewriter.Support.Vault,
  json_library: Jason,
  ciphers: [
    default:
      {Cloak.Ciphers.AES.GCM,
       tag: "AES.GCM.V1", key: Base.decode64!(System.get_env("cloak_cipher_key"))}
  ]

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :slack_rewriter, SlackRewriterWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [port: 8080],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "9AaCuT9hxM8+KOANKiqx/adOB9hiurkCXMqoA1rpwbUh6RVmy7mil6bgtP/xnpSU",
  watchers: [
    # Start the esbuild watcher by calling Esbuild.install_and_run(:default, args)
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :slack_rewriter, SlackRewriterWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/slack_rewriter_web/(live|views)/.*(ex)$",
      ~r"lib/slack_rewriter_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
